---
build_from:
  amd64: lscr.io/linuxserver/tautulli:2.17.0
  aarch64: lscr.io/linuxserver/tautulli:2.17.0
  armv7: lscr.io/linuxserver/tautulli:2.17.0
  armhf: lscr.io/linuxserver/tautulli:2.17.0
labels:
  org.opencontainers.image.title: "Tautulli"
  org.opencontainers.image.description: "Tautulli add-on for Home Assistant"
  org.opencontainers.image.source: "https://github.com/halali/ha-apps"
  org.opencontainers.image.licenses: "MIT"
args:
  BUILD_ARCH:
    - amd64
    - aarch64
    - armv7
    - armhf
