---
build_from:
  amd64: lscr.io/linuxserver/prowlarr:2.5.2.5491-ls155
labels:
  org.opencontainers.image.title: "Prowlarr"
  org.opencontainers.image.description: "Prowlarr add-on for Home Assistant"
  org.opencontainers.image.source: "https://github.com/halali/ha-apps"
  org.opencontainers.image.licenses: "MIT"
