---
build_from:
  amd64: lscr.io/linuxserver/radarr:5.11.0
  aarch64: lscr.io/linuxserver/radarr:5.11.0
  armv7: lscr.io/linuxserver/radarr:5.11.0
  armhf: lscr.io/linuxserver/radarr:5.11.0
labels:
  org.opencontainers.image.title: "Radarr"
  org.opencontainers.image.description: "Radarr add-on pre Home Assistant"
  org.opencontainers.image.source: "https://github.com/halali/ha-apps"
  org.opencontainers.image.licenses: "MIT"
args:
  BUILD_ARCH:
    - amd64
    - aarch64
    - armv7
    - armhf
