---
build_from:
  amd64: lscr.io/linuxserver/radarr:6.3.0.10514-ls312
  aarch64: lscr.io/linuxserver/radarr:6.3.0.10514-ls312
  armv7: lscr.io/linuxserver/radarr:6.3.0.10514-ls312
  armhf: lscr.io/linuxserver/radarr:6.3.0.10514-ls312
labels:
  org.opencontainers.image.title: "Radarr"
  org.opencontainers.image.description: "Radarr add-on for Home Assistant"
  org.opencontainers.image.source: "https://github.com/halali/ha-apps"
  org.opencontainers.image.licenses: "MIT"
args:
  BUILD_ARCH:
    - amd64
    - aarch64
    - armv7
    - armhf
