[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/appflowy/supervisord.pid

[program:postgres]
command=/usr/local/bin/afw-postgres.sh
priority=10
autorestart=true
startretries=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:redis]
command=/usr/local/bin/afw-redis.sh
priority=10
autorestart=true
startretries=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:minio]
command=/usr/local/bin/afw-minio.sh
priority=10
autorestart=true
startretries=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:gotrue]
command=/usr/local/bin/afw-gotrue.sh
priority=30
autorestart=true
startretries=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:appflowy_cloud]
command=/usr/local/bin/afw-cloud.sh
priority=40
autorestart=true
startretries=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:appflowy_worker]
command=/usr/local/bin/afw-worker.sh
priority=45
autorestart=true
startretries=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:nginx]
command=/usr/local/bin/afw-nginx.sh
priority=50
autorestart=true
startretries=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
