---
build_from:
  amd64: ghcr.io/seerr-team/seerr:v3.2.0
labels:
  org.opencontainers.image.title: "Seerr"
  org.opencontainers.image.description: "Seerr add-on for Home Assistant"
  org.opencontainers.image.source: "https://github.com/halali/ha-apps"
  org.opencontainers.image.licenses: "MIT"
