---
build_from:
  amd64: lscr.io/linuxserver/lidarr:3.1.0.4875-ls27
  aarch64: lscr.io/linuxserver/lidarr:3.1.0.4875-ls27
  armv7: lscr.io/linuxserver/lidarr:3.1.0.4875-ls27
  armhf: lscr.io/linuxserver/lidarr:3.1.0.4875-ls27
labels:
  org.opencontainers.image.title: "Lidarr"
  org.opencontainers.image.description: "Lidarr add-on for Home Assistant"
  org.opencontainers.image.source: "https://github.com/halali/ha-apps"
  org.opencontainers.image.licenses: "MIT"
args:
  BUILD_ARCH:
    - amd64
    - aarch64
    - armv7
    - armhf
